# Site settings
name: Jordi Blasco
description: "HPC Solutions Architect"
url: ""
collections:
  posts:
    output:   true
limit_posts: 10
future: true

# Delete the lines you don't need
# about 5 elements are recomended
github_username:  jordiblasco
twitter_username: HPCKP
linkedin_username: jordiblascopallares
bitbucket_username: jordiblasco
#skype: jordi-blasco
#blog_url: "/blog"
email: jordi.blasco@gmail.com

# typed.js options
loop: True
loop-count: False # Set False for infinite loop, or set any number for a finite loop.
type-speed: 10
start-delay: 200
delete-delay: 1000
lines:
  - text: "Computational Physicist from the University of Barcelona"
  - text: "Co-Founder and CEO of Do IT Now - New Zealand"
  - text: "Co-Founder and CTO of HPCNow!"
  - text: "Founder of HPC Knowledge Portal"
  - text: "Developer of sNow! Cluster Manager"
  - text: "Founder of Skylabs NZ"
  - text: "Active member of Code Club"
  - text: "Member of Auckland Astronomical Society"

avatar: yes
avatar_img_path: "imgs/avatar.png"

front_img: yes
front_img_path: "imgs/background.jpg"
#front_img_path: "https://external.url/image.jpg"

favicon_img: yes
favicon_img_path: "imgs/favicon.ico"
#favicon_img_path: "https://external.url/favicon.ico"

# Build settings
markdown: kramdown
permalink: pretty
